# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        contact:
            index_name: contact_%kernel.environment%
            properties:
                firstName: ~
                lastName: ~
                email: ~
                favorite: ~
                contactPhones:
                    type: "object"
                    properties:
                        phone: ~
            persistence:
                # the driver can be orm, mongodb or phpcr
                driver: orm
                model: App\Entity\Contact
                provider: ~
                finder: ~
                elastica_to_model_transformer:
                    ignore_missing: true

