twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_5_layout.html.twig
    globals:
        contact_profile_photos_url: '%contact_profile_photos_url%'
when@test:
    twig:
        strict_variables: true
