services:

  nginx:
    container_name: REVENDO_nginx
    build: ./.docker/nginx
    ports:
      - '5002:80'
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  php:
    user: ${UID:-1000}:${GID:-1000}
    container_name: REVENDO_php
    build: ./.docker/php
    volumes:
      - ./:/var/www/html

  mysql:
    container_name: REVENDO_mysql
    build: ./.docker/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=local"
    volumes:
      - ./:/app
      - db-data:/var/lib/mysql
    ports:
      - "33320:3306"

  mailhog:
    container_name: REVENDO_mailhog
    build: ./.docker/mailhog
    ports:
      - "8502:8025"

  elasticsearch:
    container_name: REVENDO_elasticsearch
    build: ./.docker/elasticsearch
    ports: [ '9220:9200', '9330:9300' ]
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - 'es-data:/usr/share/elasticsearch/data'

  kibana:
    container_name: REVENDO_kibana
    build: ./.docker/kibana
    ports: [ '5620:5601' ]
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on: [ 'elasticsearch' ]

volumes:
  db-data:
  es-data:

