when@dev:
    parameters:
        contact_profile_photos_directory: '%kernel.project_dir%/public/uploads/contacts/'

when@test:
    parameters:
        contact_profile_photos_directory: '%kernel.project_dir%/public/uploads/contacts-testing/'
